manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Xoffio/
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: xo-status-fx
      import: app/west.yml
  self:
    path: config
